project:
  type: book
  output-dir: docs

book:
  title: "hhcr_book"
  author: "Jane Doe"
  date: "5/5/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
execute:
  freeze: auto
  
bibliography: references.bib

format:
  html:
    theme: cosmo
    



